FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# SafetyMap

Polls is a simple API allowing consumers to view polls and vote in them.

## Accident on map

### Get accident on map [POST]

+ Request (application/json)

    {
        "top_right_lat": 16.459665
        "top_right_lon": 102.862628
        "bottom_left_lat": 16.393556
        "bottom_left_lon": 102.798941
    }

+ Response 200 (application/json)
    + Headers

    + Body
        [
            {
                "area": 1,
                "accidentpoint_no": 1,
                "acc_time": "2015/10/01 00:00:00",
                "inform_time": "2015-09-30T17:00:00.000Z",
                "rescue_time": "2015-09-30T17:00:00.000Z",
                "finish_time": "2015-09-30T17:00:00.000Z",
                "people_wound": 5,
                "people_dead": 1,
                "location_latitude": 16.439621,
                "location_longitude": 102.833737,
                "location_desc": "ขอนแก่น1",
                "cause_type_id": 1,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 1,
                "ems_operation_no": "",
                "petient_no": 1,
                "hn": "0000000001",
                "citizenid": "1111111111111",
                "surname": "ชูพงศ์",
                "name": "อรสา",
                "sex": "male",
                "age": 25,
                "patient_type_id": 1,
                "patient_type_desc": "",
                "vehicle_no": 1,
                "vehicle_license_no": "1กข-0001",
                "vehicle_license_province": "ขอนแก่น",
                "vehicle_type_id": 1,
                "vehicle_desc": "",
                "cause_type_name": "อื่น ๆ",
                "er_name": "โรงพยาบาล 1",
                "ems_name": "หน่วยกู้ภัย 1"
            },
            {
                "area": 1,
                "accidentpoint_no": 2,
                "acc_time": "2015/10/02 00:00:00",
                "inform_time": "2015-10-01T17:00:00.000Z",
                "rescue_time": "2015-10-01T17:00:00.000Z",
                "finish_time": "2015-10-01T17:00:00.000Z",
                "people_wound": 2,
                "people_dead": 0,
                "location_latitude": 16.439408,
                "location_longitude": 102.799795,
                "location_desc": "ขอนแก่น2",
                "cause_type_id": 2,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 2,
                "ems_operation_no": "",
                "petient_no": 2,
                "hn": "0000000002",
                "citizenid": "1111111111112",
                "surname": "ณรงค์ฤทธิ์",
                "name": "รุ่งเรือง",
                "sex": "male",
                "age": 25,
                "patient_type_id": 2,
                "patient_type_desc": "",
                "vehicle_no": 2,
                "vehicle_license_no": "1กข-0002",
                "vehicle_license_province": "ขอนแก่น",
                "vehicle_type_id": 2,
                "vehicle_desc": "",
                "cause_type_name": "ตกจากพาหนะ",
                "er_name": "โรงพยาบาล 1",
                "ems_name": "หน่วยกู้ภัย 2"
            },
            {
                "area": 1,
                "accidentpoint_no": 4,
                "acc_time": "2015/10/04 00:00:00",
                "inform_time": "2015-10-03T17:00:00.000Z",
                "rescue_time": "2015-10-03T17:00:00.000Z",
                "finish_time": "2015-10-03T17:00:00.000Z",
                "people_wound": 4,
                "people_dead": 0,
                "location_latitude": 16.432599,
                "location_longitude": 102.834181,
                "location_desc": "ขอนแก่น4",
                "cause_type_id": 4,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 4,
                "ems_operation_no": "",
                "petient_no": 4,
                "hn": "0000000004",
                "citizenid": "1111111111114",
                "surname": "สงเจริญ",
                "name": "จิรา",
                "sex": "male",
                "age": 24,
                "patient_type_id": 4,
                "patient_type_desc": "",
                "vehicle_no": 4,
                "vehicle_license_no": "1กข-0004",
                "vehicle_license_province": "ขอนแก่น",
                "vehicle_type_id": 4,
                "vehicle_desc": "",
                "cause_type_name": "ถูกชน",
                "er_name": "โรงพยาบาล 1",
                "ems_name": "หน่วยกู้ภัย 4"
            },
            {
                "area": 1,
                "accidentpoint_no": 5,
                "acc_time": "2015/10/05 00:00:00",
                "inform_time": "2015-10-04T17:00:00.000Z",
                "rescue_time": "2015-10-04T17:00:00.000Z",
                "finish_time": "2015-10-04T17:00:00.000Z",
                "people_wound": 3,
                "people_dead": 1,
                "location_latitude": 16.43111,
                "location_longitude": 102.830631,
                "location_desc": "ขอนแก่น5",
                "cause_type_id": 5,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 5,
                "ems_operation_no": "",
                "petient_no": 5,
                "hn": "0000000005",
                "citizenid": "1111111111115",
                "surname": "ขมุนจิตร์",
                "name": "นงค์",
                "sex": "male",
                "age": 24,
                "patient_type_id": 1,
                "patient_type_desc": "",
                "vehicle_no": 5,
                "vehicle_license_no": "1กข-0005",
                "vehicle_license_province": "ขอนแก่น",
                "vehicle_type_id": 5,
                "vehicle_desc": "",
                "cause_type_name": "ชนกับอื่น ๆ",
                "er_name": "โรงพยาบาล 1",
                "ems_name": "หน่วยกู้ภัย 5"
            },
            {
                "area": 1,
                "accidentpoint_no": 6,
                "acc_time": "2015/10/06 00:00:00",
                "inform_time": "2015-10-05T17:00:00.000Z",
                "rescue_time": "2015-10-05T17:00:00.000Z",
                "finish_time": "2015-10-05T17:00:00.000Z",
                "people_wound": 5,
                "people_dead": 0,
                "location_latitude": 16.428982,
                "location_longitude": 102.844608,
                "location_desc": "ขอนแก่น6",
                "cause_type_id": 1,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 1,
                "ems_operation_no": "",
                "petient_no": 6,
                "hn": "0000000006",
                "citizenid": "1111111111116",
                "surname": "ขมุนจิตร์",
                "name": "จิรภัทร",
                "sex": "male",
                "age": 23,
                "patient_type_id": 2,
                "patient_type_desc": "",
                "vehicle_no": 6,
                "vehicle_license_no": "1กข-0006",
                "vehicle_license_province": "ขอนแก่น",
                "vehicle_type_id": 6,
                "vehicle_desc": "",
                "cause_type_name": "อื่น ๆ",
                "er_name": "โรงพยาบาล 1",
                "ems_name": "หน่วยกู้ภัย 1"
            },
            {
                "area": 1,
                "accidentpoint_no": 7,
                "acc_time": "2015/10/07 00:00:00",
                "inform_time": "2015-10-06T17:00:00.000Z",
                "rescue_time": "2015-10-06T17:00:00.000Z",
                "finish_time": "2015-10-06T17:00:00.000Z",
                "people_wound": 1,
                "people_dead": 1,
                "location_latitude": 16.424087,
                "location_longitude": 102.835956,
                "location_desc": "ขอนแก่น7",
                "cause_type_id": 2,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 2,
                "ems_operation_no": "",
                "petient_no": 7,
                "hn": "0000000007",
                "citizenid": "1111111111117",
                "surname": "ขมุนจิตร",
                "name": "วิโรจน์",
                "sex": "famale",
                "age": 22,
                "patient_type_id": 3,
                "patient_type_desc": "",
                "vehicle_no": 7,
                "vehicle_license_no": "1กข-0007",
                "vehicle_license_province": "ขอนแก่น",
                "vehicle_type_id": 7,
                "vehicle_desc": "",
                "cause_type_name": "ตกจากพาหนะ",
                "er_name": "โรงพยาบาล 1",
                "ems_name": "หน่วยกู้ภัย 2"
            },
            {
                "area": 1,
                "accidentpoint_no": 8,
                "acc_time": "2015/10/08 00:00:00",
                "inform_time": "2015-10-07T17:00:00.000Z",
                "rescue_time": "2015-10-07T17:00:00.000Z",
                "finish_time": "2015-10-07T17:00:00.000Z",
                "people_wound": 2,
                "people_dead": 0,
                "location_latitude": 16.426003,
                "location_longitude": 102.827525,
                "location_desc": "ขอนแก่น8",
                "cause_type_id": 3,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 3,
                "ems_operation_no": "",
                "petient_no": 8,
                "hn": "0000000008",
                "citizenid": "1111111111118",
                "surname": "ขมุนจิตร์",
                "name": "ภัทรวุฒิ",
                "sex": "famale",
                "age": 21,
                "patient_type_id": 4,
                "patient_type_desc": "",
                "vehicle_no": 8,
                "vehicle_license_no": "1กข-0008",
                "vehicle_license_province": "ขอนแก่น",
                "vehicle_type_id": 8,
                "vehicle_desc": "",
                "cause_type_name": "พาหนะ ล้ม คว่ำ ตก ล่ม จม",
                "er_name": "โรงพยาบาล 1",
                "ems_name": "หน่วยกู้ภัย 3"
            },
            {
                "area": 1,
                "accidentpoint_no": 9,
                "acc_time": "2015/10/09 00:00:00",
                "inform_time": "2015-10-08T17:00:00.000Z",
                "rescue_time": "2015-10-08T17:00:00.000Z",
                "finish_time": "2015-10-08T17:00:00.000Z",
                "people_wound": 3,
                "people_dead": 0,
                "location_latitude": 16.436216,
                "location_longitude": 102.828191,
                "location_desc": "ขอนแก่น9",
                "cause_type_id": 4,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 4,
                "ems_operation_no": "",
                "petient_no": 9,
                "hn": "0000000009",
                "citizenid": "1111111111119",
                "surname": "คงเพชร์",
                "name": "อภิชาติ",
                "sex": "famale",
                "age": 30,
                "patient_type_id": 1,
                "patient_type_desc": "",
                "vehicle_no": 9,
                "vehicle_license_no": "1กข-0009",
                "vehicle_license_province": "ขอนแก่น",
                "vehicle_type_id": 9,
                "vehicle_desc": "",
                "cause_type_name": "ถูกชน",
                "er_name": "โรงพยาบาล 1",
                "ems_name": "หน่วยกู้ภัย 4"
            },
            {
                "area": 1,
                "accidentpoint_no": 10,
                "acc_time": "2015/10/10 00:00:00",
                "inform_time": "2015-10-09T17:00:00.000Z",
                "rescue_time": "2015-10-09T17:00:00.000Z",
                "finish_time": "2015-10-09T17:00:00.000Z",
                "people_wound": 4,
                "people_dead": 0,
                "location_latitude": 16.416427,
                "location_longitude": 102.834403,
                "location_desc": "ขอนแก่น10",
                "cause_type_id": 5,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 1,
                "ems_operation_no": "",
                "petient_no": 10,
                "hn": "0000000010",
                "citizenid": "1111111111120",
                "surname": "คงเพชร์",
                "name": "กัลยกร",
                "sex": "male",
                "age": 29,
                "patient_type_id": 2,
                "patient_type_desc": "",
                "vehicle_no": 10,
                "vehicle_license_no": "1กข-0010",
                "vehicle_license_province": "กรุงเทพ",
                "vehicle_type_id": 10,
                "vehicle_desc": "",
                "cause_type_name": "ชนกับอื่น ๆ",
                "er_name": "โรงพยาบาล 1",
                "ems_name": "หน่วยกู้ภัย 1"
            },
            {
                "area": 1,
                "accidentpoint_no": 11,
                "acc_time": "2015/10/11 00:00:00",
                "inform_time": "2015-10-10T17:00:00.000Z",
                "rescue_time": "2015-10-10T17:00:00.000Z",
                "finish_time": "2015-10-10T17:00:00.000Z",
                "people_wound": 5,
                "people_dead": 0,
                "location_latitude": 16.433876,
                "location_longitude": 102.811996,
                "location_desc": "ขอนแก่น11",
                "cause_type_id": 1,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 2,
                "ems_operation_no": "",
                "petient_no": 11,
                "hn": "0000000011",
                "citizenid": "1111111111121",
                "surname": "คงเพชร์",
                "name": "พรณี",
                "sex": "male",
                "age": 28,
                "patient_type_id": 3,
                "patient_type_desc": "",
                "vehicle_no": 11,
                "vehicle_license_no": "1กข-0011",
                "vehicle_license_province": "กรุงเทพ",
                "vehicle_type_id": 1,
                "vehicle_desc": "",
                "cause_type_name": "อื่น ๆ",
                "er_name": "โรงพยาบาล 1",
                "ems_name": "หน่วยกู้ภัย 2"
            },
            {
                "area": 1,
                "accidentpoint_no": 12,
                "acc_time": "2015/10/12 00:00:00",
                "inform_time": "2015-10-11T17:00:00.000Z",
                "rescue_time": "2015-10-11T17:00:00.000Z",
                "finish_time": "2015-10-11T17:00:00.000Z",
                "people_wound": 12,
                "people_dead": 0,
                "location_latitude": 16.442387,
                "location_longitude": 102.821314,
                "location_desc": "ขอนแก่น12",
                "cause_type_id": 2,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 3,
                "ems_operation_no": "",
                "petient_no": 12,
                "hn": "0000000012",
                "citizenid": "1111111111122",
                "surname": "คงเพชร์",
                "name": "ประทีป",
                "sex": "famale",
                "age": 27,
                "patient_type_id": 4,
                "patient_type_desc": "",
                "vehicle_no": 12,
                "vehicle_license_no": "1กข-0012",
                "vehicle_license_province": "กรุงเทพ",
                "vehicle_type_id": 2,
                "vehicle_desc": "",
                "cause_type_name": "ตกจากพาหนะ",
                "er_name": "โรงพยาบาล 1",
                "ems_name": "หน่วยกู้ภัย 3"
            },
            {
                "area": 1,
                "accidentpoint_no": 13,
                "acc_time": "2015/10/13 00:00:00",
                "inform_time": "2015-10-12T17:00:00.000Z",
                "rescue_time": "2015-10-12T17:00:00.000Z",
                "finish_time": "2015-10-12T17:00:00.000Z",
                "people_wound": 4,
                "people_dead": 1,
                "location_latitude": 16.445366,
                "location_longitude": 102.847714,
                "location_desc": "ขอนแก่น13",
                "cause_type_id": 3,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 4,
                "ems_operation_no": "",
                "petient_no": 13,
                "hn": "0000000013",
                "citizenid": "1111111111123",
                "surname": "พฤกษ์เนรมิตร",
                "name": "วีระชัย",
                "sex": "famale",
                "age": 26,
                "patient_type_id": 1,
                "patient_type_desc": "",
                "vehicle_no": 13,
                "vehicle_license_no": "1กข-0013",
                "vehicle_license_province": "กรุงเทพ",
                "vehicle_type_id": 3,
                "vehicle_desc": "",
                "cause_type_name": "พาหนะ ล้ม คว่ำ ตก ล่ม จม",
                "er_name": "โรงพยาบาล 1",
                "ems_name": "หน่วยกู้ภัย 4"
            },
            {
                "area": 1,
                "accidentpoint_no": 14,
                "acc_time": "2015/10/14 00:00:00",
                "inform_time": "2015-10-13T17:00:00.000Z",
                "rescue_time": "2015-10-13T17:00:00.000Z",
                "finish_time": "2015-10-13T17:00:00.000Z",
                "people_wound": 4,
                "people_dead": 0,
                "location_latitude": 16.42047,
                "location_longitude": 102.834403,
                "location_desc": "ขอนแก่น14",
                "cause_type_id": 4,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 5,
                "ems_operation_no": "",
                "petient_no": 14,
                "hn": "0000000014",
                "citizenid": "1111111111124",
                "surname": "พฤกษ์เนรมิต",
                "name": "ธีรศักดิ์",
                "sex": "famale",
                "age": 25,
                "patient_type_id": 2,
                "patient_type_desc": "",
                "vehicle_no": 14,
                "vehicle_license_no": "1กข-0014",
                "vehicle_license_province": "ขอนแก่น",
                "vehicle_type_id": 4,
                "vehicle_desc": "",
                "cause_type_name": "ถูกชน",
                "er_name": "โรงพยาบาล 1",
                "ems_name": "หน่วยกู้ภัย 5"
            },
            {
                "area": 1,
                "accidentpoint_no": 15,
                "acc_time": "2015/10/15 00:00:00",
                "inform_time": "2015-10-14T17:00:00.000Z",
                "rescue_time": "2015-10-14T17:00:00.000Z",
                "finish_time": "2015-10-14T17:00:00.000Z",
                "people_wound": 5,
                "people_dead": 1,
                "location_latitude": 16.421534,
                "location_longitude": 102.825972,
                "location_desc": "ขอนแก่น15",
                "cause_type_id": 5,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 0,
                "ems_operation_no": "",
                "petient_no": 15,
                "hn": "0000000015",
                "citizenid": "1111111111125",
                "surname": "แซ่ลิ่ม",
                "name": "พัชนี",
                "sex": "male",
                "age": 24,
                "patient_type_id": 3,
                "patient_type_desc": "",
                "vehicle_no": 15,
                "vehicle_license_no": "1กข-0015",
                "vehicle_license_province": "ขอนแก่น",
                "vehicle_type_id": 5,
                "vehicle_desc": "",
                "cause_type_name": "ชนกับอื่น ๆ",
                "er_name": "โรงพยาบาล 1",
                "ems_name": null
            },
            {
                "area": 1,
                "accidentpoint_no": 16,
                "acc_time": "2015/10/16 00:00:00",
                "inform_time": "2015-10-15T17:00:00.000Z",
                "rescue_time": "2015-10-15T17:00:00.000Z",
                "finish_time": "2015-10-15T17:00:00.000Z",
                "people_wound": 6,
                "people_dead": 0,
                "location_latitude": 16.422172,
                "location_longitude": 102.82087,
                "location_desc": "ขอนแก่น16",
                "cause_type_id": 1,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 1,
                "ems_operation_no": "",
                "petient_no": 16,
                "hn": "0000000016",
                "citizenid": "1111111111126",
                "surname": "แซ่ลิ่ม",
                "name": "วรลักษณ์",
                "sex": "male",
                "age": 24,
                "patient_type_id": 4,
                "patient_type_desc": "",
                "vehicle_no": 16,
                "vehicle_license_no": "1กข-0016",
                "vehicle_license_province": "ขอนแก่น",
                "vehicle_type_id": 6,
                "vehicle_desc": "",
                "cause_type_name": "อื่น ๆ",
                "er_name": "โรงพยาบาล 1",
                "ems_name": "หน่วยกู้ภัย 1"
            },
            {
                "area": 1,
                "accidentpoint_no": 17,
                "acc_time": "2015/10/17 00:00:00",
                "inform_time": "2015-10-16T17:00:00.000Z",
                "rescue_time": "2015-10-16T17:00:00.000Z",
                "finish_time": "2015-10-16T17:00:00.000Z",
                "people_wound": 2,
                "people_dead": 1,
                "location_latitude": 16.4208697,
                "location_longitude": 102.8313468,
                "location_desc": "ขอนแก่น17",
                "cause_type_id": 2,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 2,
                "ems_operation_no": "",
                "petient_no": 17,
                "hn": "0000000017",
                "citizenid": "1111111111127",
                "surname": "โพธิ์ระมาด",
                "name": "พัชราภรณ์",
                "sex": "male",
                "age": 24,
                "patient_type_id": 1,
                "patient_type_desc": "",
                "vehicle_no": 17,
                "vehicle_license_no": "1กข-0017",
                "vehicle_license_province": "ขอนแก่น",
                "vehicle_type_id": 7,
                "vehicle_desc": "",
                "cause_type_name": "ตกจากพาหนะ",
                "er_name": "โรงพยาบาล 1",
                "ems_name": "หน่วยกู้ภัย 2"
            },
            {
                "area": 1,
                "accidentpoint_no": 18,
                "acc_time": "2015/10/18 00:00:00",
                "inform_time": "2015-10-17T17:00:00.000Z",
                "rescue_time": "2015-10-17T17:00:00.000Z",
                "finish_time": "2015-10-17T17:00:00.000Z",
                "people_wound": 1,
                "people_dead": 0,
                "location_latitude": 16.4192442235294,
                "location_longitude": 102.831784945588,
                "location_desc": "ขอนแก่น18",
                "cause_type_id": 3,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 3,
                "ems_operation_no": "",
                "petient_no": 18,
                "hn": "0000000018",
                "citizenid": "1111111111128",
                "surname": "แซ่ลิ่ม",
                "name": "รัตน์ติยา",
                "sex": "male",
                "age": 23,
                "patient_type_id": 2,
                "patient_type_desc": "",
                "vehicle_no": 18,
                "vehicle_license_no": "1กข-0018",
                "vehicle_license_province": "ขอนแก่น",
                "vehicle_type_id": 8,
                "vehicle_desc": "",
                "cause_type_name": "พาหนะ ล้ม คว่ำ ตก ล่ม จม",
                "er_name": "โรงพยาบาล 1",
                "ems_name": "หน่วยกู้ภัย 3"
            },
            {
                "area": 1,
                "accidentpoint_no": 19,
                "acc_time": "2015/10/19 00:00:00",
                "inform_time": "2015-10-18T17:00:00.000Z",
                "rescue_time": "2015-10-18T17:00:00.000Z",
                "finish_time": "2015-10-18T17:00:00.000Z",
                "people_wound": 3,
                "people_dead": 1,
                "location_latitude": 16.4176187470588,
                "location_longitude": 102.832223091176,
                "location_desc": "ขอนแก่น19",
                "cause_type_id": 4,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 4,
                "ems_operation_no": "",
                "petient_no": 19,
                "hn": "0000000019",
                "citizenid": "1111111111129",
                "surname": "แซ่ลิ่ม",
                "name": "เอ้ง",
                "sex": "famale",
                "age": 22,
                "patient_type_id": 3,
                "patient_type_desc": "",
                "vehicle_no": 19,
                "vehicle_license_no": "1กข-0019",
                "vehicle_license_province": "ขอนแก่น",
                "vehicle_type_id": 9,
                "vehicle_desc": "",
                "cause_type_name": "ถูกชน",
                "er_name": "โรงพยาบาล 1",
                "ems_name": "หน่วยกู้ภัย 4"
            },
            {
                "area": 1,
                "accidentpoint_no": 20,
                "acc_time": "2015/10/20 00:00:00",
                "inform_time": "2015-10-19T17:00:00.000Z",
                "rescue_time": "2015-10-19T17:00:00.000Z",
                "finish_time": "2015-10-19T17:00:00.000Z",
                "people_wound": 4,
                "people_dead": 0,
                "location_latitude": 16.4159932705882,
                "location_longitude": 102.832661236765,
                "location_desc": "ขอนแก่น20",
                "cause_type_id": 5,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 5,
                "ems_operation_no": "",
                "petient_no": 20,
                "hn": "0000000020",
                "citizenid": "1111111111130",
                "surname": "จิตนุพงศ์",
                "name": "มณฑา",
                "sex": "male",
                "age": 21,
                "patient_type_id": 4,
                "patient_type_desc": "",
                "vehicle_no": 20,
                "vehicle_license_no": "1กข-0020",
                "vehicle_license_province": "ขอนแก่น",
                "vehicle_type_id": 10,
                "vehicle_desc": "",
                "cause_type_name": "ชนกับอื่น ๆ",
                "er_name": "โรงพยาบาล 1",
                "ems_name": "หน่วยกู้ภัย 5"
            },
            {
                "area": 1,
                "accidentpoint_no": 21,
                "acc_time": "2015/10/21 00:00:00",
                "inform_time": "2015-10-20T17:00:00.000Z",
                "rescue_time": "2015-10-20T17:00:00.000Z",
                "finish_time": "2015-10-20T17:00:00.000Z",
                "people_wound": 5,
                "people_dead": 1,
                "location_latitude": 16.4143677941176,
                "location_longitude": 102.833099382353,
                "location_desc": "ขอนแก่น21",
                "cause_type_id": 1,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 1,
                "ems_operation_no": "",
                "petient_no": 21,
                "hn": "0000000021",
                "citizenid": "1111111111131",
                "surname": "เอี่ยมคง",
                "name": "ลัดดา",
                "sex": "male",
                "age": 30,
                "patient_type_id": 1,
                "patient_type_desc": "",
                "vehicle_no": 21,
                "vehicle_license_no": "1กข-0021",
                "vehicle_license_province": "ขอนแก่น",
                "vehicle_type_id": 1,
                "vehicle_desc": "",
                "cause_type_name": "อื่น ๆ",
                "er_name": "โรงพยาบาล 1",
                "ems_name": "หน่วยกู้ภัย 1"
            },
            {
                "area": 1,
                "accidentpoint_no": 22,
                "acc_time": "2015/10/22 00:00:00",
                "inform_time": "2015-10-21T17:00:00.000Z",
                "rescue_time": "2015-10-21T17:00:00.000Z",
                "finish_time": "2015-10-21T17:00:00.000Z",
                "people_wound": 6,
                "people_dead": 1,
                "location_latitude": 16.4127423176471,
                "location_longitude": 102.833537527941,
                "location_desc": "ขอนแก่น22",
                "cause_type_id": 2,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 2,
                "ems_operation_no": "",
                "petient_no": 22,
                "hn": "0000000022",
                "citizenid": "1111111111132",
                "surname": "ลีละวัฒน์",
                "name": "ทิพากร",
                "sex": "male",
                "age": 29,
                "patient_type_id": 2,
                "patient_type_desc": "",
                "vehicle_no": 22,
                "vehicle_license_no": "1กข-0022",
                "vehicle_license_province": "ขอนแก่น",
                "vehicle_type_id": 2,
                "vehicle_desc": "",
                "cause_type_name": "ตกจากพาหนะ",
                "er_name": "โรงพยาบาล 1",
                "ems_name": "หน่วยกู้ภัย 2"
            },
            {
                "area": 1,
                "accidentpoint_no": 23,
                "acc_time": "2015/10/23 00:00:00",
                "inform_time": "2015-10-22T17:00:00.000Z",
                "rescue_time": "2015-10-22T17:00:00.000Z",
                "finish_time": "2015-10-22T17:00:00.000Z",
                "people_wound": 3,
                "people_dead": 2,
                "location_latitude": 16.4111168411765,
                "location_longitude": 102.833975673529,
                "location_desc": "ขอนแก่น23",
                "cause_type_id": 3,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 3,
                "ems_operation_no": "",
                "petient_no": 23,
                "hn": "0000000023",
                "citizenid": "1111111111133",
                "surname": "รัศมีประเสริฐ",
                "name": "ธนธิป",
                "sex": "famale",
                "age": 28,
                "patient_type_id": 3,
                "patient_type_desc": "",
                "vehicle_no": 23,
                "vehicle_license_no": "1กข-0023",
                "vehicle_license_province": "กรุงเทพ",
                "vehicle_type_id": 3,
                "vehicle_desc": "",
                "cause_type_name": "พาหนะ ล้ม คว่ำ ตก ล่ม จม",
                "er_name": "โรงพยาบาล 1",
                "ems_name": "หน่วยกู้ภัย 3"
            },
            {
                "area": 1,
                "accidentpoint_no": 24,
                "acc_time": "2015/10/24 00:00:00",
                "inform_time": "2015-10-23T17:00:00.000Z",
                "rescue_time": "2015-10-23T17:00:00.000Z",
                "finish_time": "2015-10-23T17:00:00.000Z",
                "people_wound": 6,
                "people_dead": 1,
                "location_latitude": 16.4094913647059,
                "location_longitude": 102.834413819118,
                "location_desc": "ขอนแก่น24",
                "cause_type_id": 4,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 4,
                "ems_operation_no": "",
                "petient_no": 24,
                "hn": "0000000024",
                "citizenid": "1111111111134",
                "surname": "ธรรมมิกะกุล",
                "name": "เจียมจิตต์",
                "sex": "male",
                "age": 27,
                "patient_type_id": 4,
                "patient_type_desc": "",
                "vehicle_no": 24,
                "vehicle_license_no": "1กข-0024",
                "vehicle_license_province": "กรุงเทพ",
                "vehicle_type_id": 4,
                "vehicle_desc": "",
                "cause_type_name": "ถูกชน",
                "er_name": "โรงพยาบาล 1",
                "ems_name": "หน่วยกู้ภัย 4"
            },
            {
                "area": 1,
                "accidentpoint_no": 25,
                "acc_time": "2015/10/25 00:00:00",
                "inform_time": "2015-10-24T17:00:00.000Z",
                "rescue_time": "2015-10-24T17:00:00.000Z",
                "finish_time": "2015-10-24T17:00:00.000Z",
                "people_wound": 1,
                "people_dead": 2,
                "location_latitude": 16.4078658882353,
                "location_longitude": 102.834851964706,
                "location_desc": "ขอนแก่น25",
                "cause_type_id": 5,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 5,
                "ems_operation_no": "",
                "petient_no": 25,
                "hn": "0000000025",
                "citizenid": "1111111111135",
                "surname": "จุติมงคล",
                "name": "สุเนตรา",
                "sex": "male",
                "age": 26,
                "patient_type_id": 1,
                "patient_type_desc": "",
                "vehicle_no": 25,
                "vehicle_license_no": "1กข-0025",
                "vehicle_license_province": "กรุงเทพ",
                "vehicle_type_id": 5,
                "vehicle_desc": "",
                "cause_type_name": "ชนกับอื่น ๆ",
                "er_name": "โรงพยาบาล 1",
                "ems_name": "หน่วยกู้ภัย 5"
            },
            {
                "area": 1,
                "accidentpoint_no": 26,
                "acc_time": "2015/10/26 00:00:00",
                "inform_time": "2015-10-25T17:00:00.000Z",
                "rescue_time": "2015-10-25T17:00:00.000Z",
                "finish_time": "2015-10-25T17:00:00.000Z",
                "people_wound": 2,
                "people_dead": 1,
                "location_latitude": 16.4062404117647,
                "location_longitude": 102.835290110294,
                "location_desc": "ขอนแก่น26",
                "cause_type_id": 1,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 1,
                "ems_operation_no": "",
                "petient_no": 26,
                "hn": "0000000026",
                "citizenid": "1111111111136",
                "surname": "แซ่อ่อน",
                "name": "พงศ์ศักดิ์",
                "sex": "famale",
                "age": 25,
                "patient_type_id": 2,
                "patient_type_desc": "",
                "vehicle_no": 26,
                "vehicle_license_no": "1กข-0026",
                "vehicle_license_province": "กรุงเทพ",
                "vehicle_type_id": 6,
                "vehicle_desc": "",
                "cause_type_name": "อื่น ๆ",
                "er_name": "โรงพยาบาล 1",
                "ems_name": "หน่วยกู้ภัย 1"
            },
            {
                "area": 1,
                "accidentpoint_no": 27,
                "acc_time": "2015/10/27 00:00:00",
                "inform_time": "2015-10-26T17:00:00.000Z",
                "rescue_time": "2015-10-26T17:00:00.000Z",
                "finish_time": "2015-10-26T17:00:00.000Z",
                "people_wound": 3,
                "people_dead": 0,
                "location_latitude": 16.4046149352941,
                "location_longitude": 102.835728255882,
                "location_desc": "ขอนแก่น27",
                "cause_type_id": 2,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 2,
                "ems_operation_no": "",
                "petient_no": 27,
                "hn": "0000000027",
                "citizenid": "1111111111137",
                "surname": "อัญชลีกุล",
                "name": "พันทวี",
                "sex": "famale",
                "age": 24,
                "patient_type_id": 3,
                "patient_type_desc": "",
                "vehicle_no": 27,
                "vehicle_license_no": "1กข-0027",
                "vehicle_license_province": "ขอนแก่น",
                "vehicle_type_id": 7,
                "vehicle_desc": "",
                "cause_type_name": "ตกจากพาหนะ",
                "er_name": "โรงพยาบาล 1",
                "ems_name": "หน่วยกู้ภัย 2"
            },
            {
                "area": 1,
                "accidentpoint_no": 28,
                "acc_time": "2015/10/28 00:00:00",
                "inform_time": "2015-10-27T17:00:00.000Z",
                "rescue_time": "2015-10-27T17:00:00.000Z",
                "finish_time": "2015-10-27T17:00:00.000Z",
                "people_wound": 4,
                "people_dead": 0,
                "location_latitude": 16.4029894588235,
                "location_longitude": 102.836166401471,
                "location_desc": "ขอนแก่น28",
                "cause_type_id": 3,
                "cause_desc": "",
                "er_id": 2,
                "er_acc_no": "",
                "ems_id": 3,
                "ems_operation_no": "",
                "petient_no": 28,
                "hn": "0000000028",
                "citizenid": "1111111111138",
                "surname": "อัญชลีกุล",
                "name": "บุญเลิศ",
                "sex": "famale",
                "age": 24,
                "patient_type_id": 4,
                "patient_type_desc": "",
                "vehicle_no": 28,
                "vehicle_license_no": "1กข-0028",
                "vehicle_license_province": "ขอนแก่น",
                "vehicle_type_id": 8,
                "vehicle_desc": "",
                "cause_type_name": "พาหนะ ล้ม คว่ำ ตก ล่ม จม",
                "er_name": "โรงพยาบาล 2",
                "ems_name": "หน่วยกู้ภัย 3"
            },
            {
                "area": 1,
                "accidentpoint_no": 29,
                "acc_time": "2015/10/29 00:00:00",
                "inform_time": "2015-10-28T17:00:00.000Z",
                "rescue_time": "2015-10-28T17:00:00.000Z",
                "finish_time": "2015-10-28T17:00:00.000Z",
                "people_wound": 5,
                "people_dead": 0,
                "location_latitude": 16.4013639823529,
                "location_longitude": 102.836604547059,
                "location_desc": "ขอนแก่น29",
                "cause_type_id": 4,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 4,
                "ems_operation_no": "",
                "petient_no": 29,
                "hn": "0000000029",
                "citizenid": "1111111111139",
                "surname": "อัญชลีกุล",
                "name": "ตรีชานนท์",
                "sex": "famale",
                "age": 24,
                "patient_type_id": 1,
                "patient_type_desc": "",
                "vehicle_no": 29,
                "vehicle_license_no": "1กข-0029",
                "vehicle_license_province": "ขอนแก่น",
                "vehicle_type_id": 9,
                "vehicle_desc": "",
                "cause_type_name": "ถูกชน",
                "er_name": "โรงพยาบาล 1",
                "ems_name": "หน่วยกู้ภัย 4"
            },
            {
                "area": 1,
                "accidentpoint_no": 30,
                "acc_time": "2015/10/30 00:00:00",
                "inform_time": "2015-10-29T17:00:00.000Z",
                "rescue_time": "2015-10-29T17:00:00.000Z",
                "finish_time": "2015-10-29T17:00:00.000Z",
                "people_wound": 6,
                "people_dead": 0,
                "location_latitude": 16.3997385058824,
                "location_longitude": 102.837042692647,
                "location_desc": "ขอนแก่น30",
                "cause_type_id": 5,
                "cause_desc": "",
                "er_id": 1,
                "er_acc_no": "",
                "ems_id": 5,
                "ems_operation_no": "",
                "petient_no": 30,
                "hn": "0000000030",
                "citizenid": "1111111111140",
                "surname": "อัญชลีกุล",
                "name": "ควรคิด",
                "sex": "famale",
                "age": 23,
                "patient_type_id": 2,
                "patient_type_desc": "",
                "vehicle_no": 30,
                "vehicle_license_no": "1กข-0030",
                "vehicle_license_province": "ขอนแก่น",
                "vehicle_type_id": 10,
                "vehicle_desc": "",
                "cause_type_name": "ชนกับอื่น ๆ",
                "er_name": "โรงพยาบาล 1",
                "ems_name": "หน่วยกู้ภัย 5"
            },
            {
                "area": 1,
                "accidentpoint_no": 31,
                "acc_time": "2015/10/31 00:00:00",
                "inform_time": "2015-10-30T17:00:00.000Z",
                "rescue_time": "2015-10-30T17:00:00.000Z",
                "finish_time": "2015-10-30T17:00:00.000Z",
                "people_wound": 7,
                "people_dead": 0,
                "location_latitude": 16.3981130294118,
                "location_longitude": 102.837480838235,
                "location_desc": "ขอนแก่น31",
                "cause_type_id": 1,
                "cause_desc": "",
                "er_id": 2,
                "er_acc_no": "",
                "ems_id": 1,
                "ems_operation_no": "",
                "petient_no": 31,
                "hn": "0000000031",
                "citizenid": "1111111111141",
                "surname": "บุญรุ่งโรจน์",
                "name": "อนุชิดา",
                "sex": "famale",
                "age": 22,
                "patient_type_id": 3,
                "patient_type_desc": "",
                "vehicle_no": 31,
                "vehicle_license_no": "1กข-0031",
                "vehicle_license_province": "ขอนแก่น",
                "vehicle_type_id": 1,
                "vehicle_desc": "",
                "cause_type_name": "อื่น ๆ",
                "er_name": "โรงพยาบาล 2",
                "ems_name": "หน่วยกู้ภัย 1"
            },
            {
                "area": 1,
                "accidentpoint_no": 32,
                "acc_time": "2015/11/01 00:00:00",
                "inform_time": "2015-10-31T17:00:00.000Z",
                "rescue_time": "2015-10-31T17:00:00.000Z",
                "finish_time": "2015-10-31T17:00:00.000Z",
                "people_wound": 8,
                "people_dead": 0,
                "location_latitude": 16.3964875529412,
                "location_longitude": 102.837918983824,
                "location_desc": "ขอนแก่น32",
                "cause_type_id": 2,
                "cause_desc": "",
                "er_id": 3,
                "er_acc_no": "",
                "ems_id": 2,
                "ems_operation_no": "",
                "petient_no": 32,
                "hn": "0000000032",
                "citizenid": "1111111111142",
                "surname": "เอียดแก้ว",
                "name": "ศิรดา",
                "sex": "male",
                "age": 21,
                "patient_type_id": 4,
                "patient_type_desc": "",
                "vehicle_no": 32,
                "vehicle_license_no": "1กข-0032",
                "vehicle_license_province": "ขอนแก่น",
                "vehicle_type_id": 2,
                "vehicle_desc": "",
                "cause_type_name": "ตกจากพาหนะ",
                "er_name": "โรงพยาบาล 3",
                "ems_name": "หน่วยกู้ภัย 2"
            },
            {
                "area": 1,
                "accidentpoint_no": 33,
                "acc_time": "2015/11/02 00:00:00",
                "inform_time": "2015-11-01T17:00:00.000Z",
                "rescue_time": "2015-11-01T17:00:00.000Z",
                "finish_time": "2015-11-01T17:00:00.000Z",
                "people_wound": 2,
                "people_dead": 0,
                "location_latitude": 16.3948620764706,
                "location_longitude": 102.838357129412,
                "location_desc": "ขอนแก่น33",
                "cause_type_id": 3,
                "cause_desc": "",
                "er_id": 4,
                "er_acc_no": "",
                "ems_id": 3,
                "ems_operation_no": "",
                "petient_no": 33,
                "hn": "0000000033",
                "citizenid": "1111111111143",
                "surname": "ผาสุข",
                "name": "ภัสรา",
                "sex": "male",
                "age": 30,
                "patient_type_id": 1,
                "patient_type_desc": "",
                "vehicle_no": 33,
                "vehicle_license_no": "1กข-0033",
                "vehicle_license_province": "ขอนแก่น",
                "vehicle_type_id": 3,
                "vehicle_desc": "",
                "cause_type_name": "พาหนะ ล้ม คว่ำ ตก ล่ม จม",
                "er_name": "โรงพยาบาล 4",
                "ems_name": "หน่วยกู้ภัย 3"
            }
        ]


## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
